### ISSUE TITLE
Narrow light band from the right in a dark theme

### ISSUE THREAD

**Issue by MikeWi11s0n** [NayemAhmedNiloy/Bard#1]
Hi! Thanks for the app. On my Samsung with a screen resolution of 2340x1080, when I select the dark theme, a small, narrow bright strip appears on the right side. It looks like white with some color mixed in, but in reality it's probably white like in the screenshot, it just looks that way to me. I suspect that in the dark theme, the background or stretching does not work properly on the full screen, resulting in this strip. I would greatly appreciate it if you could fix this.

![Screenshot_20230714-115126](https://github.com/nayemahmedniloy/Bard/assets/139548551/73c6f7a1-81f0-4576-b93a-865417065ad7)

**Comment by nayemahmedniloy** [comment]
Hi @MikeWi11s0n Thank you so much for using this app. 
**A new React Native version has been released. I hope you won't face the problem anymore. This version has file upload and download functionality. Enjoy the full experience of _Google Bard_ into a native android application.**
